image: node:16.3.0-alpine

cache:
  paths:
    - node_modules
  key: project

stages:
  - install
  - test
  - deploy

install:
  stage: install
  script: npm ci
  only:
    - merge_requests
    - main

pages:
  stage: deploy
  script:
    - npm run build
    - mv docs/.vuepress/dist public
  artifacts:
    paths:
      - public
  only:
    - main
