image: node:16.14

stages:
  - deploy
  - post

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv docs/.vuepress/dist public
  artifacts:
    paths:
      - public
  only:
    - main

release:
  image: registry.gitlab.com/nosana-ci/tools/containers/semver
  stage: post
  script: release.sh
  only:
    - main

cacheflush:
  stage: post
  script:
    - |
      curl -X POST \
        --header "Content-Type: application/json" \
        --header "Authorization: Bearer $CF_TOKEN_CACHE_PURGE_NOSANA_IO" \
        --data '{"purge_everything":true}' \
        "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID_NOSANA_IO/purge_cache"
  only:
    - main
