image: node:16.7

stages:
  - deploy
  - release

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv docs/.vuepress/dist public
  artifacts:
    paths:
      - public
  only:
    - main

release:
  image: registry.gitlab.com/nosana-ci/tools/containers/semver
  stage: release
  script: release.sh
  only:
    - main
