image: node:16.7

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - mv docs/.vuepress/dist public
  artifacts:
    paths:
      - public
  only:
    - main
